function cirular_layout(){myDiagram.div=null;myDiagram=GO(go.Diagram,"myDiagramDiv",{initialAutoScale:go.Diagram.Uniform,"undoManager.isEnabled":!0,layout:GO(go.CircularLayout)});myOverview.div=null;myOverview=GO(go.Overview,"myOverviewDIV",{observed:myDiagram});myDiagram.nodeTemplateMap.add("",GO(go.Node,"Vertical",{layerName:"Foreground",doubleClick:function(){send_newGraph("\u5c5e\u6027")}},GO(go.Picture,{source:"./img/ddqp.svg",margin:new go.Margin(0,20,2,0),opacity:0},new go.Binding("source",
"vertex_type",function(a){console.log(vertex_type)})),GO(go.Picture,{source:"./img/ddqp.svg",margin:new go.Margin(-41,0,2,0),opacity:0}),GO(go.Picture,{source:"./img/ddqp.svg",margin:new go.Margin(-41,-20,2,0),opacity:0}),GO(go.Picture,{source:"./img/triangle.svg",margin:new go.Margin(-10,-50,2,0),opacity:0},new go.Binding("source","isExpand",function(a){if(1==a)return"./img/triangle_in.svg";if(2==a)return"./img/triangle_out.svg";if(3==V)return"./img/triangle.svg"}),new go.Binding("opacity","isExpand",
function(a){return 0<a?1:0})),GO(go.Shape,"Ellipse",{name:"node_shape",stroke:"#006ADF",fill:"#006ADF",width:60,cursor:"pointer",height:60,portId:"",strokeWidth:5},{toolTip:tooltipTemplate},new go.Binding("fill","d_fill",function(a){return""==a?"#006ADF":a}),new go.Binding("stroke","d_stroke"),new go.Binding("width"),new go.Binding("height")),GO(go.Picture,{name:"icon_enetity",source:"./img/account.svg",margin:new go.Margin(-40,0,0,0),opacity:1},new go.Binding("source","icon",geoFunc),new go.Binding("width",
"width",function(a){return.6*a}),new go.Binding("height","height",function(a){return.5*a}),new go.Binding("margin","height",function(a){return new go.Margin(.78*-a,0,0,0)})),GO(go.Panel,"Auto",{margin:12},new go.Binding("margin","width",function(a){return 12*a/60*1.2}),GO(go.Shape,"Rectangle",{fill:null,stroke:null,margin:new go.Margin(5,0,0,0)},(new go.Binding("fill","isSelected",function(a){return a?"#FFC106":null})).ofObject("")),GO(go.TextBlock,{margin:6},new go.Binding("text","text",function(a){return setText(a)}),
new go.Binding("font","font_size",function(a){return a+"px helvetica, bold Arial, sans-serif"}),(new go.Binding("stroke","isSelected",function(a){return a?"#fff":"#333"})).ofObject(""))),{selectionAdornmentTemplate:GO(go.Adornment,"Vertical",GO(go.Shape,"RoundedRectangle",{width:100,height:130,fill:null,stroke:null,strokeWidth:5,margin:new go.Margin(0,0,0,0)}),GO(go.Placeholder))},GO(go.Shape,"RoundedRectangle",{name:"entity_label",margin:new go.Margin(-44,0,0,130),fill:"red",cursor:"pointer",width:60,
height:18,opacity:0},{},{toolTip:tooltipTemplate_label1},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[0].style.width?1:0}),new go.Binding("fill","tags",function(a){return a[0].style.fill}),new go.Binding("stroke","tags",function(a){return a[0].style.stroke})),GO(go.Shape,"RoundedRectangle",{name:"entity_label2",margin:new go.Margin(2,0,0,140),fill:"red",cursor:"pointer",width:60,height:18,opacity:0},{toolTip:tooltipTemplate_label2},new go.Binding("opacity","tags",function(a){return 0==
labelisShow?0:0<a[1].style.width?1:0}),new go.Binding("fill","tags",function(a){return a[1].style.fill}),new go.Binding("stroke","tags",function(a){return a[1].style.stroke})),GO(go.Shape,"RoundedRectangle",{name:"entity_label3",margin:new go.Margin(2,0,0,130),fill:"red",cursor:"pointer",width:60,height:18,opacity:0},{toolTip:tooltipTemplate_label3},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[2].style.width?1:0}),new go.Binding("fill","tags",function(a){return a[2].style.fill}),
new go.Binding("stroke","tags",function(a){return a[2].style.stroke})),GO(go.TextBlock,{name:"entity_label_text1",text:"",cursor:"pointer",opacity:0,stroke:"#333",margin:new go.Margin(-59,0,0,120)},{toolTip:tooltipTemplate_label1},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[0].style.width?1:0}),new go.Binding("text","tags",function(a){return 5<strlen(a[0].text)?a[0].text.slice(0,2)+"...":a[0].text}),new go.Binding("stroke","tags",function(a){return a[0].style.font_color})),
GO(go.TextBlock,{name:"entity_label_text_x1",text:"X",cursor:"pointer",opacity:0,stroke:"#fff",margin:new go.Margin(-18,0,0,170)},{click:function(a,b){delete_lable(1)}},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[0].style.width?1:0})),GO(go.TextBlock,{name:"entity_label_text2",text:"",cursor:"pointer",opacity:0,stroke:"#333",margin:new go.Margin(5,0,0,120)},{toolTip:tooltipTemplate_label2},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[1].style.width?
1:0}),new go.Binding("text","tags",function(a){return 5<strlen(a[1].text)?a[1].text.slice(0,2):a[1].text}),new go.Binding("stroke","tags",function(a){return a[1].style.font_color})),GO(go.TextBlock,{name:"entity_label_text_x2",text:"X",cursor:"pointer",opacity:0,stroke:"#fff",margin:new go.Margin(-17,0,0,180)},{click:function(a,b){delete_lable(2)}},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[1].style.width?1:0})),GO(go.TextBlock,{name:"entity_label_text3",text:"",cursor:"pointer",
opacity:0,stroke:"#333",margin:new go.Margin(5,0,0,120)},{toolTip:tooltipTemplate_label3},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[2].style.width?1:0}),new go.Binding("text","tags",function(a){return 5<strlen(a[2].text)?a[2].text.slice(0,2):a[2].text}),new go.Binding("stroke","tags",function(a){return a[2].style.font_color})),GO(go.TextBlock,{name:"entity_label_text_x3",text:"X",cursor:"pointer",opacity:0,stroke:"#fff",margin:new go.Margin(-17,0,0,170)},{click:function(a,
b){delete_lable(3)}},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[2].style.width?1:0}))));myDiagram.nodeTemplateMap.add("square",GO(go.Node,"Auto",GO(go.Shape,"RoundedRectangle",{width:120,height:64,fill:"#fff",stroke:"#D55500",strokeWidth:2},new go.Binding("fill"),new go.Binding("stroke")),GO(go.TextBlock,{name:"icon_label",opacity:1,margin:8,maxSize:new go.Size(200,NaN),wrap:go.TextBlock.WrapFit,stroke:"#D55500",editable:!0},(new go.Binding("text")).makeTwoWay()),new go.Binding("stroke")));
myDiagram.linkTemplate=GO(go.Link,{cursor:"pointer"},{doubleClick:function(){send_newGraph("\u5c5e\u6027")}},{toolTip:tooltipTemplate_link},GO(go.Shape,{name:"edge_standard",toArrow:"standard",stroke:"#BDBDBD",fill:"#BDBDBD",opacity:1},new go.Binding("stroke","d_stroke"),new go.Binding("strokeWidth","stroke_width"),new go.Binding("fill","d_stroke")),GO(go.Shape,{name:"link_arrow",toArrow:"standard",stroke:"#BDBDBD",fill:"#BDBDBD",visible:!1},new go.Binding("fill","d_stroke"),new go.Binding("strokeWidth",
"stroke_width"),new go.Binding("stroke","d_stroke"),new go.Binding("visible","dir",function(a){if(0===a)return!1;if(1===a)return!0;if(2===a)return!1;if(3===a)return!0})),GO(go.Shape,{name:"link_arrow",fromArrow:"Backward",stroke:"#BDBDBD",fill:"#BDBDBD",visible:!1},new go.Binding("fill","d_stroke"),new go.Binding("strokeWidth","stroke_width"),new go.Binding("stroke","d_stroke"),new go.Binding("visible","dir",function(a){if(0===a||1===a)return!1;if(2===a||3===a)return!0})),{},GO(go.TextBlock,{text:"",
name:"link_text",textAlign:"center",font:"12px helvetica, bold Arial, sans-serif",stroke:"#333",editable:!1,opacity:1,segmentOffset:new go.Point(10,NaN),segmentOrientation:go.Link.OrientUpleft,margin:4},new go.Binding("text"),new go.Binding("font","font_size",function(a){return a+"px helvetica, bold Arial, sans-serif"})))};