function _defineProperty(b,a,c){a in b?Object.defineProperty(b,a,{value:c,enumerable:!0,configurable:!0,writable:!0}):b[a]=c;return b}function x_SankeyLayout(){go.TreeLayout.call(this)}go.Diagram.inherit(x_SankeyLayout,go.TreeLayout);
x_SankeyLayout.prototype.makeNetwork=function(b){var a=go.LayeredDigraphLayout.prototype.makeNetwork.call(this,b);this.diagram.nodes.each(function(c){var d=getAutoHeightForNode(c),e=c.findObject("SHAPE");e&&(e.height=d);e=c.findObject("TEXT");var f=c.findObject("LTEXT");d="bold "+Math.max(12,Math.round(d/8))+"pt Segoe UI, sans-serif";e&&(e.font=d);f&&(f.font=d);d=a.findVertex(c);null!==d&&(c.ensureBounds(),c=c.actualBounds,d.width=c.width,d.height=c.height,d.focusY=d.height/2)});return a};
x_SankeyLayout.prototype.nodeMinColumnSpace=function(b,a){if(null===b.node){if(1<=b.edgesCount){a=1;for(b=b.edges;b.next();){var c=b.value;if(null!=c.link){b=c.link.computeThickness();b>a&&(a=b);break}}return Math.max(2,Math.ceil(a/this.columnSpacing))}return 2}return go.LayeredDigraphLayout.prototype.nodeMinColumnSpace.call(this,b,a)};x_SankeyLayout.prototype.nodeMinLayerSpace=function(b,a){return null===b.node?100:go.LayeredDigraphLayout.prototype.nodeMinLayerSpace.call(this,b,a)};
x_SankeyLayout.prototype.assignLayers=function(){go.LayeredDigraphLayout.prototype.assignLayers.call(this);for(var b=this.maxLayer,a=this.network.vertexes.iterator;a.next();){var c=a.value;0==c.destinationVertexes.count&&(c.layer=0);0==c.sourceVertexes.count&&(c.layer=b)}};x_SankeyLayout.prototype.commitLayout=function(){go.LayeredDigraphLayout.prototype.commitLayout.call(this);for(var b=this.network.edges.iterator;b.next();){var a=b.value.link;a&&a.curve===go.Link.Bezier&&a.invalidateRoute()}};
var animation=new go.Animation;animation.easing=go.Animation.EaseLinear;
function fast_sankey_layout(){var b;graph_layout_type=1;myDiagram.div=null;myDiagram=GO(go.Diagram,"myDiagramDiv",{initialAutoScale:go.Diagram.Uniform,"animationManager.isEnabled":!1,ModelChanged:function(a){},layout:GO(x_SankeyLayout,{layerSpacing:500,alignment:go.TreeLayout.AlignmentStart})});myOverview.div=null;myOverview=GO(go.Overview,"myOverviewDIV",{observed:myDiagram});myDiagram.nodeTemplateMap.add("",GO(go.Node,"Vertical",{locationObjectName:"SHAPE",locationSpot:go.Spot.MiddleLeft,layerName:"Foreground"},
{doubleClick:function(a,c){send_newGraph("\u5c5e\u6027")}},GO(go.Shape,(b={name:"SHAPE",figure:"Rectangle",stroke:null,strokeWidth:5,portId:"",fromSpot:go.Spot.RightSide,toSpot:go.Spot.LeftSide},_defineProperty(b,"portId",""),_defineProperty(b,"cursor","pointer"),_defineProperty(b,"fromLinkable",!1),_defineProperty(b,"toLinkable",!1),_defineProperty(b,"width",20),_defineProperty(b,"opacity",1),b),{toolTip:tooltipTemplate},new go.Binding("fill","d_fill"),new go.Binding("stroke","d_stroke")),GO(go.Panel,
"Auto",{name:"node_text",visible:!1},GO(go.Shape,"Rectangle",{fill:null,stroke:null},(new go.Binding("fill","isSelected",function(a){return a?"#FFC106":null})).ofObject("")),GO(go.TextBlock,{margin:3},new go.Binding("text","text"),new go.Binding("font","font_size",function(a){return a+"px helvetica, bold Arial, sans-serif"}),(new go.Binding("stroke","isSelected",function(a){return a?"#FFF":"#333"})).ofObject(""))),{selectionAdornmentTemplate:GO(go.Adornment,"Auto",GO(go.Shape,"RoundedRectangle",{width:100,
height:130,fill:null,stroke:null,strokeWidth:5,margin:new go.Margin(0,0,0,0)}),GO(go.Placeholder))}));myDiagram.nodeTemplateMap.add("square",GO(go.Node,"Auto",GO(go.Shape,"RoundedRectangle",{width:120,height:64,fill:"#fff",stroke:"#D55500",strokeWidth:2},new go.Binding("d_fill"),new go.Binding("d_stroke")),GO(go.TextBlock,{name:"icon_label",visible:1,margin:8,maxSize:new go.Size(200,NaN),wrap:go.TextBlock.WrapFit,stroke:"#D55500",editable:!0},(new go.Binding("text")).makeTwoWay()),new go.Binding("stroke",
"d_stroke")));b=GO(go.Adornment,"Link",GO(go.Shape,{isPanelMain:!0,fill:null,stroke:"blue",strokeWidth:3}));myDiagram.linkTemplate=GO(go.Link,go.Link.Bezier,{selectionAdornmentTemplate:b,fromEndSegmentLength:150,toEndSegmentLength:150,adjusting:go.Link.End},{doubleClick:function(){send_newGraph("\u5c5e\u6027")}},{toolTip:tooltipTemplate_link},(new go.Binding("points")).makeTwoWay(),GO(go.Shape,{opacity:1,isPanelMain:!0,stroke:"#BDBDBD",strokeWidth:1,fill:"#BDBDBD"},new go.Binding("fill","d_stroke"),
new go.Binding("stroke","d_stroke")),GO(go.Shape,{isPanelMain:!0,stroke:"white",strokeWidth:3,name:"PIPE",strokeDashArray:[10,10],opacity:0}),GO(go.TextBlock,{name:"link_text",textAlign:"center",stroke:"#000",visible:!1},new go.Binding("font","font_size",function(a){return a+"px helvetica, bold Arial, sans-serif"}),new go.Binding("text","text",function(a){return a.replace(/(\r\n)|(\n)/g,"  ")})),GO(go.Shape,{name:"link_arrow",toArrow:"standard",stroke:"#BDBDBD",fill:"#BDBDBD",visible:!1},new go.Binding("fill",
"d_stroke"),new go.Binding("stroke","d_stroke"),new go.Binding("visible","dir",function(a){if(0===a)return!1;if(1===a)return!0;if(2===a)return!1;if(3===a)return!0})),GO(go.Shape,{name:"link_arrow",fromArrow:"Backward",stroke:"#BDBDBD",fill:"#BDBDBD",visible:!1},new go.Binding("fill","d_stroke"),new go.Binding("stroke","d_stroke"),new go.Binding("visible","dir",function(a){if(0===a||1===a)return!1;if(2===a||3===a)return!0})))};