function _instanceof(a,b){return null!=b&&"undefined"!==typeof Symbol&&b[Symbol.hasInstance]?!!b[Symbol.hasInstance](a):a instanceof b}var myWholeModel;
function f_v_layout(){myDiagram.div=null;myDiagram=GO(go.Diagram,"myDiagramDiv",{contentAlignment:go.Spot.Center,initialAutoScale:go.Diagram.Uniform,layout:GO(VirtualizedForceDirectedLayout,{defaultSpringLength:140,maxIterations:200}),"undoManager.isEnabled":!0,"animationManager.isEnabled":!1});myOverview.div=null;myOverview=GO(go.Overview,"myOverviewDIV",{observed:myDiagram});myDiagram.nodeTemplateMap.add("",GO(go.Node,"Vertical",{isLayoutPositioned:!1},(new go.Binding("position","bounds",function(a,
b){return 1==b.part.data.isLocking?(console.log(b.part.data),new go.Point(b.part.data.loc.x,b.part.data.loc.y)):a.position})).makeTwoWay(function(a,b){return new go.Rect(a.x,a.y,b.bounds.width,b.bounds.height)}),{layerName:"Foreground",click:function(a,b){},doubleClick:function(){send_newGraph("\u5c5e\u6027")}},new go.Binding("visible"),GO(go.Shape,"Ellipse",{name:"node_shape",stroke:"#fff",fill:"#006ADF",width:60,cursor:"pointer",height:60,portId:"",strokeWidth:5},{toolTip:tooltipTemplate},new go.Binding("fill",
"d_fill",function(a){return""==a?go.Brush.randomColor():a}),(new go.Binding("fill","isHighlighted",function(a,b){return a?"red":b.part.data.d_fill})).ofObject(),new go.Binding("width"),new go.Binding("height")),GO(go.Picture,{name:"node_",source:"./img/account.svg",margin:new go.Margin(-40,0,0,0),visible:!1},new go.Binding("source","icon",geoFunc),new go.Binding("width","width",function(a){return.6*a}),new go.Binding("height","height",function(a){return.5*a}),new go.Binding("margin","height",function(a){return new go.Margin(.78*
-a,0,0,0)})),GO(go.Panel,"Auto",{name:"node_text",margin:12,visible:!1},new go.Binding("margin","width",function(a){return 12*a/60*1.2}),GO(go.Shape,"Rectangle",{fill:null,stroke:null,margin:new go.Margin(5,0,0,0)},(new go.Binding("fill","isSelected",function(a){return a?"#FFC106":null})).ofObject("")),GO(go.TextBlock,{margin:6,font:"14px helvetica, bold Arial, sans-serif"},new go.Binding("text","text",function(a){return a}),new go.Binding("font","font_size",function(a){return a+"px helvetica, bold Arial, sans-serif"}),
(new go.Binding("stroke","isSelected",function(a){return a?"#fff":"#000"})).ofObject(""))),{selectionAdornmentTemplate:GO(go.Adornment,"Vertical",GO(go.Shape,"RoundedRectangle",{width:100,height:130,fill:null,stroke:null,strokeWidth:5,margin:new go.Margin(0,0,0,0)}),GO(go.Placeholder))},{selectionAdorned:!1}));myDiagram.linkTemplate=GO(go.Link,{cursor:"pointer",isLayoutPositioned:!1},{doubleClick:function(){send_newGraph("\u5c5e\u6027")}},{toolTip:tooltipTemplate_link},GO(go.Shape,{name:"link_arrow",
toArrow:"standard",stroke:"#BDBDBD",fill:"#BDBDBD",visible:!1},new go.Binding("fill","d_stroke",function(a){return a}),new go.Binding("strokeWidth","stroke_width"),new go.Binding("stroke","d_stroke",function(a){return a}),new go.Binding("visible","dir",function(a){if(0===a)return!1;if(1===a)return!0;if(2===a)return!1;if(3===a)return!0})),GO(go.Shape,{name:"link_arrow",fromArrow:"Backward",stroke:"#BDBDBD",fill:"#BDBDBD",visible:!1},new go.Binding("fill","d_stroke",function(a){return a}),new go.Binding("stroke",
"d_stroke",function(a){return a}),new go.Binding("strokeWidth","stroke_width"),new go.Binding("visible","dir",function(a){if(0===a||1===a)return!1;if(2===a||3===a)return!0})),GO(go.Shape,{name:"edge_shape",opacity:1,isPanelMain:!0,stroke:"#BDBDBD",strokeWidth:1,fill:"#BDBDBD"},new go.Binding("fill","d_stroke",function(a){return a}),new go.Binding("stroke","money",function(a){return 1E7<a?"red":1E6<a?"orange":1E5<a?"green":"#ccc"}),new go.Binding("strokeWidth","stroke_width")),{},GO(go.TextBlock,{name:"link_text",
text:"",textAlign:"center",font:"10px helvetica, bold Arial, sans-serif",stroke:"#ccc",editable:!1,opacity:1,segmentOffset:new go.Point(10,NaN),segmentOrientation:go.Link.OrientUpleft,margin:4},new go.Binding("text"),new go.Binding("font","font",function(a){return a+"px helvetica, bold Arial, sans-serif"})));myWholeModel=GO(go.GraphLinksModel);myDiagram.layout.model=myWholeModel;myDiagram.model=GO(go.GraphLinksModel);myDiagram.isVirtualized=!0;myDiagram.addDiagramListener("ViewportBoundsChanged",
onViewportChanged);myDiagram.addDiagramListener("InitialLayoutCompleted",function(a){$(".loading").hide();$(".loading_box").hide();$(".entity_toast").css("left",document.body.clientWidth/2-100);$(".entity_toast").css("top",300);$(".entity_toast").text("\u5e03\u5c40\u5b8c\u6210");$(".entity_toast").show();setTimeout(function(){$(".entity_toast").hide()},500);a=myWholeModel.findNodeDataForKey(0);null!==a&&myDiagram.centerRect(a.bounds)});myDiagram.addDiagramListener("ChangedSelection",function(a){ChangedSelection_fuc()})}
function computeDocumentBounds(a){var b=new go.Rect;a=a.nodeDataArray;for(var c=0;c<a.length;c++){var d=a[c];d.bounds&&(0===c?b.set(d.bounds):b.unionRect(d.bounds))}return b}
function onViewportChanged(a){4>=myDiagram.scale?sets_sale_num(myDiagram.scale):myDiagram.scale=4;1==rendering_type&&setBottom_nav(nodeArray.length,graph_tool.nodesSelectCount(),graph_tool.nodesVisibleCount(),linkArray.length,graph_tool.edgesSelectCount(),graph_tool.edgesVisibleCount());var b=myDiagram.scale;myDiagram.nodes.each(function(g){var q=g.findObject("node_");g=g.findObject("node_text");null!==q&&(q.visible=.8>b?!1:!0);null!==g&&(g.visible=.8>b?!1:!0)});myDiagram.links.each(function(g){var q=
g.findObject("link_text");g=g.findObject("link_");null!==q&&(q.visible=.8>b?!1:!0);null!==g&&(g.visible=.8>b?!1:!0)});var c=a.diagram;a=c.viewportBounds;var d=c.model,h=c.skipsUndoManager;c.skipsUndoManager=!0;for(var e=new go.Rect,k=myWholeModel.nodeDataArray,f=0;f<k.length;f++){var l=k[f];if(l.bounds)for(l.bounds.intersectsRect(a)&&d.addNodeData(l),l=myWholeModel.linkDataArray,f=0;f<l.length;f++){var m=l[f],n=myWholeModel.getFromKeyForLinkData(m);if(void 0!==n&&(n=myWholeModel.findNodeDataForKey(n),
null!==n&&n.bounds)){var p=myWholeModel.getToKeyForLinkData(m);void 0!==p&&(p=myWholeModel.findNodeDataForKey(p),null!==p&&p.bounds&&(e.set(n.bounds),e.unionRect(p.bounds),e.intersectsRect(a)&&(d.addNodeData(n),d.addNodeData(p),d.addLinkData(m),m=c.findLinkForData(m),null!==m&&(m.fromNode.ensureBounds(),m.toNode.ensureBounds(),m.updateRoute()))))}}}c.skipsUndoManager=h;null===myRemoveTimer&&(myRemoveTimer=setTimeout(function(){removeOffscreen(c)},3E3))}var myRemoveTimer=null;
function removeOffscreen(a){myRemoveTimer=null;for(var b=a.viewportBounds,c=a.model,d=[],h=new go.Set,e=a.nodes;e.next();){var k=e.value,f=k.data;null===f||k.actualBounds.intersectsRect(b)||k.isSelected||k.linksConnected.any(function(l){return l.actualBounds.intersectsRect(b)})||(d.push(f),_instanceof(c,go.GraphLinksModel)&&h.addAll(k.linksConnected))}0<d.length&&(e=a.skipsUndoManager,a.skipsUndoManager=!0,c.removeNodeDataCollection(d),_instanceof(c,go.GraphLinksModel)&&h.each(function(l){l.isSelected||
c.removeLinkData(l.data)}),a.skipsUndoManager=e)}function VirtualizedForceDirectedLayout(){go.ForceDirectedLayout.call(this);this.isOngoing=!1;this.model=null}go.Diagram.inherit(VirtualizedForceDirectedLayout,go.ForceDirectedLayout);VirtualizedForceDirectedLayout.prototype.createNetwork=function(){return new VirtualizedForceDirectedNetwork(this)};VirtualizedForceDirectedLayout.prototype.makeNetwork=function(a){a=this.createNetwork();a.addData(this.model);return a};
VirtualizedForceDirectedLayout.prototype.commitLayout=function(){go.ForceDirectedLayout.prototype.commitLayout.call(this);this.diagram.fixedBounds=computeDocumentBounds(this.model);this.diagram.nodes.each(function(a){a.updateTargetBindings()})};function VirtualizedForceDirectedNetwork(a){go.ForceDirectedNetwork.call(this,a)}go.Diagram.inherit(VirtualizedForceDirectedNetwork,go.ForceDirectedNetwork);
VirtualizedForceDirectedNetwork.prototype.addData=function(a){if(_instanceof(a,go.GraphLinksModel)){for(var b=new go.Map,c=a.nodeDataArray,d=0;d<c.length;d++){var h=c[d],e=this.createVertex();e.data=h;b.set(a.getKeyForNodeData(h),e);this.addVertex(e)}c=a.linkDataArray;for(d=0;d<c.length;d++){h=c[d];e=b.get(a.getFromKeyForLinkData(h));var k=b.get(a.getToKeyForLinkData(h));if(null!==e&&null!==k){var f=this.createEdge();f.data=h;f.fromVertex=e;f.toVertex=k;this.addEdge(f)}}}else throw Error("can only handle GraphLinksModel data");
};VirtualizedForceDirectedNetwork.prototype.deleteArtificialVertexes=function(){};