var GO=go.GraphObject.make,def_color="#ccc";function convertPathPatternToShape(a){return a?PathPatterns.get(a):null}function convertPathPatternToColor(a){a=convertPathPatternToShape(a);return null!==a?a.stroke:"transparent"}var PathPatterns=new go.Map;
function definePathPattern(a,b,c,d,e){if("string"!==typeof a||"string"!==typeof b)throw Error("invalid name or geometry string argument: "+a+" "+b);void 0===c&&(c="black");void 0===d&&(d=1);void 0===e&&(e="square");PathPatterns.set(a,GO(go.Shape,{geometryString:b,fill:"transparent",stroke:c,strokeWidth:d,strokeCap:e}))}definePathPattern("Dash","M0 0 M3 0 L6 0","#A01CBB");
function SmarterForceDirectedLayout(){go.ForceDirectedLayout.call(this);this.radial=new RadialLayout;this.radial.layerThickness=200}go.Diagram.inherit(SmarterForceDirectedLayout,go.ForceDirectedLayout);SmarterForceDirectedLayout.prototype.needsClusterLayout=function(){go.ForceDirectedLayout.prototype.needsClusterLayout.call(this)&&(this.radial.network=this.network,this.radial.doLayout(this.diagram));return!1};
function froce_layout(){myDiagram.div=null;myDiagram=GO(go.Diagram,"myDiagramDiv",{initialAutoScale:go.Diagram.Uniform,"undoManager.isEnabled":!0,"animationManager.isEnabled":!1,"commandHandler.archetypeGroupData":{text:"Group",isGroup:!0,color:"blue"},layout:GO(go.ForceDirectedLayout,{defaultSpringLength:50,maxIterations:100})});myOverview.div=null;myOverview=GO(go.Overview,"myOverviewDIV",{observed:myDiagram});myDiagram.nodeTemplateMap.add("",GO(go.Node,"Vertical",{visible:!0,layerName:"Foreground",
click:function(a,b){},doubleClick:function(){send_newGraph("\u5c5e\u6027")}},new go.Binding("visible"),(new go.Binding("location","loc",go.Point.parse)).makeTwoWay(go.Point.stringify),GO(go.Picture,{source:"./img/triangle.svg",margin:new go.Margin(-10,-50,2,0),opacity:0},new go.Binding("source","isExpand",function(a){if(1==a)return"./img/triangle_in.svg";if(2==a)return"./img/triangle_out.svg";if(3==V)return"./img/triangle.svg"}),new go.Binding("opacity","isExpand",function(a){return 0<a?1:0})),GO(go.Shape,
"Ellipse",{name:"node_shape",stroke:"#fff",fill:"#006ADF",width:60,cursor:"pointer",height:60,portId:"",strokeWidth:5},{toolTip:tooltipTemplate},new go.Binding("fill","d_fill",function(a){return""==a?"#006ADF":a}),new go.Binding("stroke","d_stroke"),new go.Binding("width"),new go.Binding("height")),GO(go.Picture,{name:"icon_enetity",source:"./img/account.svg",margin:new go.Margin(-40,0,0,0),opacity:1},new go.Binding("source","icon",geoFunc),new go.Binding("width","width",function(a){return.6*a}),
new go.Binding("height","height",function(a){return.5*a}),new go.Binding("margin","height",function(a){return new go.Margin(.78*-a,0,0,0)})),GO(go.Panel,"Auto",{margin:12},new go.Binding("margin","width",function(a){return 12*a/60*1.2}),GO(go.Shape,"Rectangle",{fill:null,stroke:null,margin:new go.Margin(5,0,0,0)},(new go.Binding("fill","isSelected",function(a){return a?"#FFC106":null})).ofObject("")),GO(go.TextBlock,{margin:6},new go.Binding("text","text",function(a){return a}),(new go.Binding("stroke",
"isSelected",function(a){return a?"#fff":"#333"})).ofObject(""))),{selectionAdornmentTemplate:GO(go.Adornment,"Vertical",GO(go.Shape,"RoundedRectangle",{width:100,height:130,fill:null,stroke:null,strokeWidth:5,margin:new go.Margin(0,0,0,0)}),GO(go.Placeholder))},GO(go.Shape,"RoundedRectangle",{name:"entity_label",margin:new go.Margin(-44,0,0,130),fill:"red",cursor:"pointer",width:60,height:18,opacity:0},{},{toolTip:tooltipTemplate_label1},new go.Binding("opacity","tags",function(a){return 0==labelisShow?
0:0<a[0].style.width?1:0}),new go.Binding("margin","width",function(a){return 30==a?new go.Margin(-24,0,0,130):new go.Margin(-44,0,0,130)}),new go.Binding("fill","tags",function(a){return a[0].style.fill}),new go.Binding("stroke","tags",function(a){return a[0].style.stroke})),GO(go.Shape,"RoundedRectangle",{name:"entity_label2",margin:new go.Margin(2,0,0,140),fill:"red",cursor:"pointer",width:60,height:18,opacity:0},{toolTip:tooltipTemplate_label2},new go.Binding("opacity","tags",function(a){return 0==
labelisShow?0:0<a[1].style.width?1:0}),new go.Binding("fill","tags",function(a){return a[1].style.fill}),new go.Binding("stroke","tags",function(a){return a[1].style.stroke})),GO(go.Shape,"RoundedRectangle",{name:"entity_label3",margin:new go.Margin(2,0,0,130),fill:"red",cursor:"pointer",width:60,height:18,opacity:0},{toolTip:tooltipTemplate_label3},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[2].style.width?1:0}),new go.Binding("fill","tags",function(a){return a[2].style.fill}),
new go.Binding("stroke","tags",function(a){return a[2].style.stroke})),GO(go.TextBlock,{name:"entity_label_text1",text:"",cursor:"pointer",opacity:0,stroke:"#fff",margin:new go.Margin(-59,0,0,120)},{toolTip:tooltipTemplate_label1},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[0].style.width?1:0}),new go.Binding("text","tags",function(a){return 5<strlen(a[0].text)?a[0].text.slice(0,2)+"...":a[0].text}),new go.Binding("stroke","tags",function(a){return a[0].style.font_color})),
GO(go.TextBlock,{name:"entity_label_text_x1",text:"X",cursor:"pointer",opacity:0,stroke:"#fff",margin:new go.Margin(-18,0,0,170)},{click:function(a,b){delete_lable(1)}},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[0].style.width?1:0})),GO(go.TextBlock,{name:"entity_label_text2",text:"",cursor:"pointer",opacity:0,stroke:"#333",margin:new go.Margin(5,0,0,120)},{toolTip:tooltipTemplate_label2},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[1].style.width?
1:0}),new go.Binding("text","tags",function(a){return 5<strlen(a[1].text)?a[1].text.slice(0,2):a[1].text}),new go.Binding("stroke","tags",function(a){return a[1].style.font_color})),GO(go.TextBlock,{name:"entity_label_text_x2",text:"X",cursor:"pointer",opacity:0,stroke:"#fff",margin:new go.Margin(-17,0,0,180)},{click:function(a,b){delete_lable(2)}},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[1].style.width?1:0})),GO(go.TextBlock,{name:"entity_label_text3",text:"",cursor:"pointer",
opacity:0,stroke:"#333",margin:new go.Margin(5,0,0,120)},{toolTip:tooltipTemplate_label3},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[2].style.width?1:0}),new go.Binding("text","tags",function(a){return 5<strlen(a[2].text)?a[2].text.slice(0,2):a[2].text}),new go.Binding("stroke","tags",function(a){return a[2].style.font_color})),GO(go.TextBlock,{name:"entity_label_text_x3",text:"X",cursor:"pointer",opacity:0,stroke:"#fff",margin:new go.Margin(-17,0,0,170)},{click:function(a,
b){delete_lable(3)}},new go.Binding("opacity","tags",function(a){return 0==labelisShow?0:0<a[2].style.width?1:0})),{selectionAdorned:!1}));myDiagram.groupTemplate=GO(go.Group,"Vertical",{selectionObjectName:"PANEL",ungroupable:!0},GO(go.TextBlock,{font:"bold 19px sans-serif",isMultiline:!1,editable:!0},(new go.Binding("text","text")).makeTwoWay(),new go.Binding("stroke","color")),GO(go.Panel,"Auto",{name:"PANEL"},GO(go.Shape,"Rectangle",{fill:null,stroke:"#ccc",strokeWidth:3,portId:"",cursor:"pointer"}),
GO(go.Placeholder,{margin:10,background:"transparent"})));myDiagram.nodeTemplateMap.add("square",GO(go.Node,"Auto",GO(go.Shape,"RoundedRectangle",{width:120,height:64,fill:"#fff",stroke:"#D55500",strokeWidth:2},new go.Binding("fill"),new go.Binding("stroke")),GO(go.TextBlock,{name:"icon_label",opacity:1,margin:8,maxSize:new go.Size(200,NaN),wrap:go.TextBlock.WrapFit,stroke:"#D55500",editable:!0},(new go.Binding("text")).makeTwoWay()),new go.Binding("stroke")));myDiagram.linkTemplate=GO(go.Link,{cursor:"pointer"},
{doubleClick:function(){send_newGraph("\u5c5e\u6027")}},{toolTip:tooltipTemplate_link},GO(go.Shape,{name:"link_arrow",toArrow:"standard",stroke:"#BDBDBD",fill:"#BDBDBD",visible:!1},new go.Binding("fill","d_stroke",function(a){return a}),new go.Binding("strokeWidth","stroke_width"),new go.Binding("stroke","d_stroke",function(a){return a}),new go.Binding("visible","dir",function(a){if(0===a)return!1;if(1===a)return!0;if(2===a)return!1;if(3===a)return!0})),GO(go.Shape,{name:"link_arrow",fromArrow:"Backward",
stroke:"#BDBDBD",fill:"#BDBDBD",visible:!1},new go.Binding("fill","d_stroke",function(a){return a}),new go.Binding("stroke","d_stroke",function(a){return a}),new go.Binding("strokeWidth","stroke_width"),new go.Binding("visible","dir",function(a){if(0===a||1===a)return!1;if(2===a||3===a)return!0})),GO(go.Shape,{name:"edge_shape",opacity:1,isPanelMain:!0,stroke:"#BDBDBD",strokeWidth:1,fill:"#BDBDBD"},new go.Binding("fill","d_stroke",function(a){return a}),new go.Binding("stroke","d_stroke",function(a){return a}),
new go.Binding("strokeWidth","stroke_width")),{},GO(go.TextBlock,{name:"link_text",text:"",textAlign:"center",font:"12px helvetica, bold Arial, sans-serif",stroke:"#333",editable:!1,opacity:1,segmentOffset:new go.Point(10,NaN),segmentOrientation:go.Link.OrientUpleft,margin:4},new go.Binding("text"),new go.Binding("font","font")))};