/*
 qq:820115719  autor xiaotian  weixin:wywin2021*/
function blobToDataURL(a,b){var c=new FileReader;c.onload=function(d){b(d.target.result)};c.readAsDataURL(a)}
var graph_tool={copySelectData:0,setDataPro:function(a,b,c){myDiagram.model.setDataProperty(a,b,c)},disableAllDraw:function(){var a=myDiagram.toolManager.findTool("DragCreating");null!==a&&(a.isEnabled=!1);a=myDiagram.toolManager.findTool("FreehandDrawing");null!==a&&(a.isEnabled=!1)},onMouseLeaveNode:function(a,b){null==b||_gasInstance.isShowNodeText||(a=b.findObject("GRAPHPICTURENODEKEY"),void 0!=a&&(a.visible=!1),a=b.findObject("GRAPHPICTURENODENAME"),void 0!=a&&(a.visible=!1))},setVisibleNodeCanLayout:function(){myDiagram.nodes.each(function(a){a.visible?
a.data.locking||(a.data.isLayoutPositioned=!0):a.data.isLayoutPositioned=!1})},setNodeCanLayout:function(a){myDiagram.nodes.each(function(b){b.data.locking||(b.part.isLayoutPositioned=a)})},setNodeCanLayoutByKey:function(a,b){myDiagram.nodes.each(function(c){b.map(function(d){c.data.key==d.key&&(c.part.isLayoutPositioned=a,graph_tool.setDataPro(c.data,"locking",a))})})},graphtoJson:function(){return myDiagram.model.toJson()},getNodesCount:function(){return myDiagram.nodes.count},getEdgesCount:function(){return myDiagram.links.count},
nodesVisibleCount:function(){var a=0;myDiagram.nodes.each(function(b){b.visible||a++});return a},edgesVisibleCount:function(){var a=0;myDiagram.links.each(function(b){b.visible||a++});return a},nodesSelectCount:function(){var a=0;myDiagram.nodes.each(function(b){b.isSelected&&a++});return a},edgesSelectCount:function(){var a=0;myDiagram.links.each(function(b){b.isSelected&&a++});return a},edges:function(){var a=[];myDiagram.links.each(function(b){a.push(b.data)});return a},findNodeForKey:function(a){return myDiagram.findNodeForKey(a)},
getcurrentNode:function(){for(var a=[],b=myDiagram.nodes;b.next();){var c=b.value;c.isSelected&&(a=c.data)}return a},getcurrentNodes:function(){for(var a=[],b=myDiagram.nodes;b.next();){var c=b.value;c.isSelected&&a.push(c.data)}return a},getcurrentEdge:function(){for(var a=[],b=myDiagram.links;b.next();){var c=b.value;c.isSelected&&(a=c.data)}return a},getcurrentEdges:function(){for(var a=[],b=myDiagram.links;b.next();){var c=b.value;c.isSelected&&a.push(c.data)}return a},groupSelection:function(){myDiagram.commandHandler.groupSelection()},
unGroupSelection:function(){myDiagram.commandHandler.ungroupSelection()},deleteSelection:function(){myDiagram.commandHandler.deleteSelection()},undo:function(){console.log(1111);myDiagram.commandHandler.undo()},redo:function(){myDiagram.commandHandler.redo()},copySelection:function(){myDiagram.commandHandler.copySelection();graph_tool.copySelectData=1},pasteSelection:function(){myDiagram.commandHandler.pasteSelection();graph_tool.copySelectData=0;myDiagram.scale+=.001},decreaseZoom:function(){if(0>
myDiagram.scale)return!1;myDiagram.scale-=.1;console.log(myDiagram.scale);.01>myDiagram.scale&&(myDiagram.scale=.01);sets_sale_num(myDiagram.scale)},increaseZoom:function(){if(4<myDiagram.scale)return!1;myDiagram.scale+=.1;sets_sale_num(myDiagram.scale)},setZomm:function(a){myDiagram.scale=a},selectAll:function(){myDiagram.nodes.each(function(a){a.isSelected=!0});myDiagram.links.each(function(a){a.isSelected=!0})},reverseSelected:function(){myDiagram.nodes.each(function(a){a.isSelected=!a.isSelected});
myDiagram.links.each(function(a){a.isSelected=!a.isSelected})},myCallback:function(a){var b=window.URL.createObjectURL(a),c=document.createElement("a");c.style="display: none";c.href=b;c.download="mySVGFile.svg";void 0!==window.navigator.msSaveBlob?window.navigator.msSaveBlob(a,"mySVGFile.svg"):(document.body.appendChild(c),requestAnimationFrame(function(){c.click();window.URL.revokeObjectURL(b);document.body.removeChild(c)}))},findCommonPath:function(){function a(f,g){f.findNodesOutOf().each(function(e){e!==
f&&(e===g?(e=b.copy(),e.add(g),c.add(e)):b.contains(e)||(b.add(e),a(e,g),b.removeAt(b.count-1)))})}var b=new go.List(go.Node),c=new go.List(go.List),d=myDiagram.selection.first(),h;myDiagram.selection.each(function(f){h=f});b.add(d);a(d,h);(function(){c.each(function(f){for(var g=0;g<f.length-1;g++){var e=f.elt(g),k=f.elt(g+1);e.findLinksTo(k).each(function(l){l.isHighlighted=!0})}})})()},makeSvg:function(){var a=myDiagram.makeSvg({scale:1,background:"white"});a=(new XMLSerializer).serializeToString(a);
a=new Blob([a],{type:"image/svg+xml"});this.myCallback(a)},myCallback_img:function(a){var b=window.URL.createObjectURL(a),c=(downloadImgName?downloadImgName:new Date)+".png",d=document.createElement("a");d.style="display: none";d.href=b;d.download=c;void 0!==window.navigator.msSaveBlob?window.navigator.msSaveBlob(a,c):(document.body.appendChild(d),requestAnimationFrame(function(){d.click();window.URL.revokeObjectURL(b);document.body.removeChild(d)}))},uploadImg:function(a){},makeBlob_toParent:function(a){myDiagram.makeImageData({background:"#fff",
returnType:"blob",scale:download_scale,callback:this.toParent_callBack})},toParent_callBack:function(a,b){blobToDataURL(a,function(c){graph_tool.graphtoJson();c={g_pic:c,g_json:JSON.stringify(updateData())};1==source_client_type?(c.guid=Client_guid,callBackToClient(c)):window.parent.postMessage(c,"*")})},makeBlob:function(a){if(1==a)return myDiagram.makeImageData({background:"#1285FD",returnType:"blob",scale:.8,callback:this.uploadImg}),!1;console.log(myDiagram.documentBounds);myDiagram.makeImageData({background:"#fff",
returnType:"blob",scale:.9,callback:this.myCallback_img,maxSize:new go.Size(myDiagram.documentBounds.width,myDiagram.documentBounds.height)})}};