/*
 qq:820115719  autor xiaotian  weixin:wywin2021*/
function _defineProperty(a,d,b){d in a?Object.defineProperty(a,d,{value:b,enumerable:!0,configurable:!0,writable:!0}):a[d]=b;return a}var deepClone=function deepClone(a){var b=Array.isArray(a),c="[object Object]"===Object.prototype.toString.call(a);if(b){var g=[];for(b=0;b<a.length;b++)g[b]=deepClone(a[b]);return g}if(c){b={};for(g in a)b[g]=deepClone(a[g]);return b}return a};Object.prototype.deepClone=function(){return deepClone(this)};Object.defineProperty(Object.prototype,"deepClone",{enumerable:!1});
function merge_link_method(a){var d=[],b=myDiagram.model.linkDataArray.deepClone();console.log(nodeArray);b.map(function(e){e.type==a.data.filed.type&&d.push(e)});var c={};d.forEach(function(e){1==a.data.methods&&(-1===Object.keys(c).indexOf(e.from+"_"+e.to)&&-1===Object.keys(c).indexOf(e.to+"_"+e.from)&&(c[e.from+"_"+e.to]=[]),-1!==Object.keys(c).indexOf(e.from+"_"+e.to)?c[e.from+"_"+e.to].push(e):c[e.to+"_"+e.from].push(e));2==a.data.methods&&(-1===Object.keys(c).indexOf(e.from+"_"+e.to)&&(c[e.from+
"_"+e.to]=[]),-1!==Object.keys(c).indexOf(e.from+"_"+e.to)&&c[e.from+"_"+e.to].push(e))});b=function(e){var h=0;a.data.filed.property&&c[e].map(function(f){f.numeric.map(function(k){k.name==a.data.filed.property.type&&(h+=k.value)})});var l={from:c[e][0].from,to:c[e][0].to,text:c[e][0].type_text+"("+c[e].length+"\u6b21)"+(0<h?h:""),list:c[e],merge_type:1,type:c[e][0].type,fill:c[e][0].d_fill,d_fill:c[e][0].d_fill,stroke:c[e][0].d_stroke,d_stroke:c[e][0].d_stroke};c[e].map(function(f){linkArray.map(function(k,
n){k.from==f.from&&k.to==f.to&&linkArray.splice(n,1)})});linkArray.push(l)};for(var g in c)b(g);myDiagram.model.linkDataArray=linkArray;setLayout(layout)}function cancel_mergeLink(a){myDiagram.model.linkDataArray.map(function(d){d.list&&-1!==a.fileds.indexOf(d.type)&&d.list.map(function(b){linkArray.push(b)})});linkArray=linkArray.filter(function(d){if(1==d.merge_type&&-1==a.fileds.indexOf(d.type)||1!=d.merge_type)return d});setLayout(layout)}
function merge_child_link(){var a=[],d=myDiagram.model.linkDataArray.deepClone(),b=graph_tool.getcurrentNodes();d.map(function(h){h.from!=b[0].key&&h.to!=b[0].key||a.push(h)});var c={};a.forEach(function(h){-1===Object.keys(c).indexOf(h.from+"_"+h.type)&&(c[h.from+"_"+h.type]=[]);c[h.from+"_"+h.type].push(h)});d=function(h){console.log(c[h]);if(0<c[h].length){e=!1;c[h].map(function(p){p.id!==c[h][0].id&&(e=!0)});if(!e)return"continue";var l={from:c[h][0].from,to:c[h][0].to,fill:c[h][0].fill,stroke:c[h][0].stroke,
d_stroke:c[h][0].d_stroke,text:c[h][0].type_text?c[h][0].type_text:c[h][0].text+"("+c[h].length+"\u6b21)",_list:c[h],merge_type:2},f=[],k="",n="";c[h].map(function(p){linkArray.map(function(r,t){r.from==p.from&&r.to==p.to&&linkArray.splice(t,1)});myDiagram.model.nodeDataArray.map(function(r){if(r.key==p.to){k=""==k?r.key:k+"_"+r.key;var t=!0;f.forEach(function(q){q.id==r.id&&(t=!1)});t&&f.push(r)}})});if(1<f.length){var m={key:k,is_group:"1",_list:f,stroke:f[0].d_stroke,fill:f[0].d_fill,d_stroke:f[0].d_stroke,
d_fill:f[0].d_fill,default_stroke:f[0].default_stroke,default_fill:f[0].default_fill,text:n,text_color:"#333333",width:60,height:60,merge_type:2};m.text="\u5408\u5e76("+f.length+")"+f[0].text+"\u7b49";l.to=k;f.map(function(p,r){k=""==k?p.key:k+"_"+p.key;n="\u5408\u5e76\u5b9e\u4f53";nodeArray.map(function(t,q){t.key==p.key&&nodeArray.splice(q,1)})});nodeArray.push(m)}linkArray.push(l)}};for(var g in c){var e;d(g)}}
function cacel_merge_child_link(){myDiagram.model.linkDataArray.map(function(a){a._list&&(a._list.map(function(d){linkArray.push(d)}),linkArray.map(function(d,b){d.from==a.from&&d.to==a.to&&2==d.merge_type&&linkArray.splice(b,1)}))});myDiagram.model.nodeDataArray.map(function(a){a._list&&(a._list.map(function(d){nodeArray.push(d)}),nodeArray.map(function(d,b){d.key==a.key&&2==d.merge_type&&nodeArray.splice(b,1)}))});console.log(nodeArray);myDiagram.model.nodeDataArray=nodeArray;myDiagram.model.linkDataArray=
linkArray;setLayout(layout)}function get_graph_links_type(){var a=[],d=[];myDiagram.model.linkDataArray.map(function(b){a.push(JSON.stringify({type:b.type,type_key:b.type_key,type_text:b.type_text}))});Array.from(new Set(a)).map(function(b){d.push(JSON.parse(b))});return d}
function get_graph_mergeLink_type(){var a=[],d=[];myDiagram.model.linkDataArray.map(function(b){b.list&&0<b.list.length&&a.push(JSON.stringify({type:b.list[0].type,type_key:b.list[0].type_key,type_text:b.list[0].type_text}))});Array.from(new Set(a)).map(function(b){d.push(JSON.parse(b))});return d}
function merge_vertex(){var a;if("ForceDirectedLayout"===layout){var d=graph_tool.getcurrentNodes(),b="\u5408\u5e76("+d.length+")"+d[0].text+"\u7b49",c="",g=[];d.map(function(l){g.push(l.key);c=""==c?l.key:c+"_"+l.key;myDiagram.model.removeNodeData(l)});var e=(a={key:c,is_group:"1",list:d,stroke:d[0].d_stroke,fill:d[0].d_fill,d_stroke:d[0].d_stroke,d_fill:d[0].d_fill,default_stroke:d[0].default_stroke,default_fill:d[0].default_fill,icon:d[0].icon,text:b,fontSize:"#333333"},_defineProperty(a,"fontSize",
"#333333"),_defineProperty(a,"width",60),_defineProperty(a,"height",60),a);myDiagram.model.addNodeData(e);var h=[];a=function(l){var f=myDiagram.model.linkDataArray[l];-1!==g.indexOf(f.from)||g.indexOf(f.to);-1!==g.indexOf(f.from)&&(h.push({from:e.key,to:f.to,c_from:f.from,text:f.text,stroke:f.stroke,fill:f.fill,d_stroke:f.d_stroke,id:f.id}),myDiagram.links.each(function(k){k.data.from==f.from&&k.data.to==f.to&&(k.visible=!1)}));-1!==g.indexOf(f.to)&&(h.push({from:f.from,to:e.key,c_to:f.to,text:f.text,
stroke:f.stroke,fill:f.fill,d_stroke:f.d_stroke,id:f.id}),myDiagram.links.each(function(k){k.data.from==f.from&&k.data.to==f.to&&(k.visible=!1)}))};for(d=0;d<myDiagram.model.linkDataArray.length;d++)a(d);h.map(function(l){myDiagram.model.linkDataArray.map(function(f){});myDiagram.model.addLinkData(l)});myDiagram.model.nodeDataArray=nodeArray;myDiagram.model.linkDataArray=linkArray}}
function cacel_merge_node(){myDiagram.model.nodeDataArray.map(function(a){if(1==a.is_group){var d=[];a.list.map(function(b){myDiagram.model.addNodeData(b)});myDiagram.model.removeNodeData(a);myDiagram.model.linkDataArray.map(function(b){b.from!=a.key&&b.to!=a.key||d.push(b)});d.map(function(b){b.c_from&&myDiagram.links.each(function(c){c.data.from==b.c_from&&c.data.to==b.to&&(c.visible=!0)});b.c_to&&myDiagram.links.each(function(c){c.data.from==b.from&&c.data.to==b.c_to&&(c.visible=!0)});myDiagram.model.linkDataArray.map(function(c){b.from==
c.from&&b.to==c.to&&myDiagram.model.removeLinkData(c)})})}})}function select_Both_ends(){graph_tool.getcurrentEdges().map(function(a){myDiagram.nodes.each(function(d){if(d.data.key==a.from||d.data.key==a.to)d.isSelected=!0})});ChangedSelection_fuc()}
function select_Both_ends_links(){var a=graph_tool.getcurrentEdges(),d=graph_tool.getcurrentNodes(),b=[];a.map(function(c){myDiagram.nodes.each(function(g){if(g.data.key==c.from||g.data.key==c.to)g.isSelected=!0});myDiagram.links.each(function(g){g.data.from==c.from&&g.data.to==c.to&&(g.isSelected=!0)})});d.map(function(c){myDiagram.nodes.each(function(g){g.data.key==c.key&&(g.isSelected=!0)});myDiagram.links.each(function(g){if(g.data.from==c.key||g.data.to==c.key)g.isSelected=!0,b.push(g.data.from),
b.push(g.data.to)})});b.map(function(c){myDiagram.nodes.each(function(g){g.data.key==c&&(g.isSelected=!0)})});ChangedSelection_fuc()}function select_links(){graph_tool.getcurrentNodes().map(function(a){myDiagram.links.each(function(d){if(d.data.from==a.key||d.data.to==a.key)d.isSelected=!0})});ChangedSelection_fuc()}function change_selectordrag(a){myDiagram.allowSelect=a}
function setEntity2hide(){var a=graph_tool.getcurrentNodes();myDiagram.nodes.each(function(d){myDiagram.model.setDataProperty(d.data,"visible",!1)});a.map(function(d){myDiagram.nodes.each(function(b){b.data.key==d.key&&myDiagram.model.setDataProperty(b.data,"visible",!0)})})}
function setSelectEntity2hide(){var a=graph_tool.getcurrentNodes(),d=graph_tool.getcurrentEdges();a.map(function(b){myDiagram.model.setDataProperty(b,"visible",!1)});d.map(function(b){hide_link_list.push(b)});myDiagram.model.linkDataArray.map(function(b){d.map(function(c){b.id==c.id&&myDiagram.model.removeLinkData(c)})})}
function show_allEntity(){myDiagram.model.nodeDataArray.map(function(a){myDiagram.model.setDataProperty(a,"visible",!0)});myDiagram.model.linkDataArray.map(function(a){myDiagram.model.setDataProperty(a,"visible",!0)});hide_link_list.map(function(a){myDiagram.model.addLinkData(a)});hide_link_list=[]}
function get_node_rows(){var a=[];myDiagram.nodes.each(function(d){var b={type:"",id:"",text:"",link_out:"",link_in:"",link_total:"",link_num_total:""},c=d.data,g=0,e=0,h=0;b.type=c.type_text;b.id=c.id;b.text=c.text;myDiagram.links.each(function(l){var f=l.data;f.from==d.key&&(g++,h++);f.to==d.key&&(e++,h++);l.numeric&&l.numeric.map(function(k){})});b.link_out=g;b.link_in=e;b.link_total=h;a.push(b)});return a}
function get_link_rows(){var a=[];myDiagram.links.each(function(d){var b={type:"",text:"",from_text:"",to_text:"",link_num:"",total_num:""},c=d.data,g=-1;b.type=c.type_text;b.text=c.text;b.from_text=graph_tool.findNodeForKey(c.from).data.text;b.to_text=graph_tool.findNodeForKey(c.to).data.text;myDiagram.links.each(function(e){e.data.type==c.type&&g++});b.total_num=0;b.link_num=g;a.push(b)});return a}
function get_link_Dimension_count(){var a=[],d=[];myDiagram.links.each(function(c){a.push(c.data.type_text)});a=get_array_ele_count(a);for(var b=0;b<a.length;b++)d.push(a[b].value);d=get_array_ele_count(d);return{types:a,counts:d}}
function get_node_Dimension_count(){var a=[],d=[],b=[],c=[],g=[],e=[],h=[],l=[];myDiagram.nodes.map(function(f){a.push(f.data.type_text);d.push(f.data.text);var k=0,n=0,m=0,p=0,r=0,t=0;myDiagram.links.each(function(q){q=q.data;q.from==f.key&&(k++,m++,t=p=0);q.to==f.key&&(n++,m++,t=r=0)});b.push(m);c.push(k);g.push(n);h.push(p);l.push(r);e.push(t)});return{types:get_array_ele_count(a),texts:get_array_ele_count(d),link_total:get_array_ele_count(b),link_out:get_array_ele_count(c),link_in:get_array_ele_count(g),
link_num_total:get_array_ele_count(e),link_num_out:get_array_ele_count(h),link_num_in:get_array_ele_count(l)}}function get_array_ele_count(a){var d=[];a=a.reduce(function(c,g){c[g]=c[g]?++c[g]:1;return c},{});for(var b in a)d.push({name:b,value:a[b]});return d}
function node_expandorcollapse(a){var d=graph_tool.getcurrentNode(),b;myDiagram.nodes.each(function(c){c.data.key==d.key&&(b=c)});b.isTreeExpanded&&"collapseTree"==a&&myDiagram.commandHandler.collapseTree(b);"expandTree"==a&&myDiagram.commandHandler.expandTree(b)}function setNodeHighlighted(a){var d=graph_tool.getcurrentNode();myDiagram.nodes.each(function(b){b.data.key==d.key&&(b.part.isHighlighted=a)})}
function set_datatoTiming_layout(){var a=[],d=[],b=[];linkArray.map(function(e){if(0<e.time){var h={name:e.to+e.time,value:[e.time,e.to+e.time],text:e.to},l={source:e.from+e.time,target:e.to+e.time,text:e.time};a.push({name:e.from+e.time,value:[e.time,e.from+e.time],text:e.from});a.push(h);d.push(l);b.push(e.time)}});var c=[];a.map(function(e){c.push(e.name)});c=Array.from(new Set(c));var g={nodes:a,links:d,yData:c,timings:b};console.log(g);return g}
function start_layout_animation(){var a=10;animation_time_out=setInterval(function(){myDiagram.startTransaction("changed Layout");myDiagram.layout.defaultElectricalCharge=a;myDiagram.commitTransaction("changed Layout");500<a?a-=20:10<=a&&500>a&&(a+=20)},100)}function stop_layout_animation(){clearInterval(animation_time_out)}
function _commonRelationship(){var a=myDiagram.selection.toArray(),d=[];myDiagram.nodes.each(function(b){var c;b.findLinksConnected().each(function(g){for(var e=0;e<a.length;e++){var h=a[e];if(g.data.from==h.data.key||g.data.to==h.data.key)c=e}});c==a.length-1&&(b.isSelected=!0,d.push(b))});return d}
function _findAllPath(){function a(g){myDiagram.clearHighlighteds();for(var e=0;e<g.count-1;e++){var h=g.get(e),l=g.get(e+1);h.findLinksTo(l).each(function(f){f.isSelected=!0})}}var d=myDiagram.selection.first(),b;myDiagram.selection.each(function(g){g.data.key!==d.data.key&&(b=g)});var c=[];(function(g,e){function h(k,n){k.findNodesOutOf().each(function(m){m!==k&&(m===n?(m=l.copy(),m.add(n),f.add(m)):l.has(m)||(l.add(m),h(m,n),l.removeAt(l.count-1)))})}var l=new go.List,f=new go.List;l.add(g);h(g,
e);return f})(d,b).each(function(g){for(var e={length:g.length,items:[]},h=0;h<g.length;h++)e.items.push(g.get(h).data);c.push(e);a(g)});return c}
function _findShortPath(a,d){function b(f){myDiagram.clearHighlighteds();for(var k=0;k<f.count-1;k++){var n=f.get(k),m=f.get(k+1);n.findLinksTo(m).each(function(p){p.isSelected=!0})}}var c=myDiagram.selection.first(),g;myDiagram.selection.each(function(f){f.data.key!==c.data.key&&(g=f)});a=function(f,k){function n(r,t){r.findNodesOutOf().each(function(q){q!==r&&(q===t?(q=m.copy(),q.add(t),p.add(q)):m.has(q)||(m.add(q),n(q,t),m.removeAt(m.count-1)))})}var m=new go.List,p=new go.List;m.add(f);n(f,k);
return p}(c,g);var e=[];a.each(function(f){for(var k={length:f.length,nodes:[],path:f},n=0;n<f.length;n++)k.nodes.push(f.get(n).data);e.push(k)});if(0!=e.length){var h=e[0].length,l=[];e.map(function(f){f.length<h&&(h=f.length)});a.each(function(f){f.length==h&&(b(f),l.push(f))});return l}};