function _createForOfIteratorHelper(a,b){var c;if("undefined"===typeof Symbol||null==a[Symbol.iterator]){if(Array.isArray(a)||(c=_unsupportedIterableToArray(a))||b&&a&&"number"===typeof a.length){c&&(a=c);var d=0;b=function(){};return{s:b,n:function(){return d>=a.length?{done:!0}:{done:!1,value:a[d++]}},e:function(h){throw h;},f:b}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}var e=!0,
f=!1,g;return{s:function(){c=a[Symbol.iterator]()},n:function(){var h=c.next();e=h.done;return h},e:function(h){f=!0;g=h},f:function(){try{e||null==c.return||c.return()}finally{if(f)throw g;}}}}
function _unsupportedIterableToArray(a,b){if(a){if("string"===typeof a)return _arrayLikeToArray(a,b);var c=Object.prototype.toString.call(a).slice(8,-1);"Object"===c&&a.constructor&&(c=a.constructor.name);if("Map"===c||"Set"===c)return Array.from(a);if("Arguments"===c||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(c))return _arrayLikeToArray(a,b)}}function _arrayLikeToArray(a,b){if(null==b||b>a.length)b=a.length;for(var c=0,d=Array(b);c<b;c++)d[c]=a[c];return d}
function geoFunc(a){return"./img/icon/"+a+".svg"}
function ChangedSelection_fuc(){2==graph_tool.getcurrentNodes().length&&(startVertex=graph_tool.getcurrentNodes()[0],endVertex=graph_tool.getcurrentNodes()[1]);1E3>nodeArray.length&&1E3>linkArray.length&&setBottom_nav(graph_tool.getNodesCount(),graph_tool.nodesSelectCount(),graph_tool.nodesVisibleCount(),graph_tool.getEdgesCount(),graph_tool.edgesSelectCount(),graph_tool.edgesVisibleCount());graph_tool.getcurrentNodes();graph_tool.getcurrentEdges();send_newGraph("\u5b9e\u4f53\u9009\u4e2d\u5185\u5bb9\u53d1\u751f\u53d8\u5316")}
myDiagram=GO(go.Diagram,"myDiagramDiv");
var myOverview=GO(go.Overview,"myOverviewDIV",{observed:myDiagram}),tooltipTemplate=GO("ToolTip",{"Border.fill":"#fff","Border.stroke":"lightgray"},GO(go.TextBlock,{stroke:"#167CF3",text:"",font:"16px sans-serif",wrap:go.TextBlock.WrapFit,desiredSize:new go.Size(200,NaN),alignment:go.Spot.Center,margin:new go.Margin(10,15,10,15)},new go.Binding("text","toolTip_text"))),tooltipTemplate_text=GO("ToolTip",{"Border.fill":"#fff","Border.stroke":"lightgray"},GO(go.TextBlock,{stroke:"#167CF3",text:"",font:"16px sans-serif",
wrap:go.TextBlock.WrapFit,desiredSize:new go.Size(200,NaN),alignment:go.Spot.Center,margin:new go.Margin(10,15,10,15)},new go.Binding("text")));function init_tooltipTemplate_label(a){return GO("ToolTip",{"Border.fill":"#fff","Border.stroke":"lightgray"},GO(go.TextBlock,{stroke:"#167CF3",text:"",font:"16px sans-serif",wrap:go.TextBlock.WrapFit,desiredSize:new go.Size(200,NaN),alignment:go.Spot.Center,margin:new go.Margin(10,15,10,15)},new go.Binding("text","tags",function(b){return b[a].text})))}
var tooltipTemplate_label1=init_tooltipTemplate_label(0),tooltipTemplate_label2=init_tooltipTemplate_label(1),tooltipTemplate_label3=init_tooltipTemplate_label(2),tooltipTemplate_link=GO("ToolTip",{"Border.fill":"#fff","Border.stroke":"lightgray"},GO(go.TextBlock,{stroke:"#167CF3",text:"",font:"16px sans-serif",wrap:go.TextBlock.WrapFit,desiredSize:new go.Size(200,NaN),alignment:go.Spot.Center,margin:new go.Margin(10,15,10,15)},new go.Binding("text","toolTip_text")));
function setLayout(a,b){$(".loading").show();$(".loading_box").show();$("#container").css("z-index",-10);$("#myDiagramDiv").css("z-index",10);$("#myDiagramDiv").show();$(".eye_c").show();$("#graph-container").hide();$("#graph-container").css("opacity",0);rendering_type=1;if("layer"==a)layer_layout();else if("mlm_layout"==a)mlm_layout();else if("fast_sankey"==a)sankey_layout_Nolayer();else if("skr_layout"==a)skr_layout();else if("p_c_layout"==a)p_c_layout();else if("Equity_layout"==a)Equity_layout();
else{if("ForceDirectedLayout"==a){3E3<=nodeArray.length||3E3<=linkArray.length?($("#myDiagramDiv").hide(),$("#graph-container").show(),rendering_type=2,renderer&&(renderer.dispose(),renderer=null),$(".node-label").remove(),$(".link-label").remove(),init_Webgl()):(f_v_layout(),myWholeModel.nodeDataArray=nodeArray,myWholeModel.linkDataArray=linkArray,myDiagram.layoutDiagram(!0));return}if("sankey"==a)sankey_layout();else if("treeLayout"==a)tree_layout();else if("cirular"==a)cirular_layout();else if("structure"==
a)structure_layout();else if("timing"==a){option.xAxis.max=Math.max.apply(null,set_datatoTiming_layout().timings);option.xAxis.min=Math.min.apply(null,set_datatoTiming_layout().timings);option.series[0].data=function(c){var d=[];c=_createForOfIteratorHelper(c);var e;try{var f=function(){var g=e.value;if(d.find(function(h){return h.name===g.name}))return"continue";d.push(g)};for(c.s();!(e=c.n()).done;)f()}catch(g){c.e(g)}finally{c.f()}return d}(set_datatoTiming_layout().nodes);option.series[0].links=
set_datatoTiming_layout().links;option.yAxis.data=set_datatoTiming_layout().yData;myChart.setOption(option);$("#container").css("z-index",10);$("#myDiagramDiv").css("z-index",-10);".loading".hide();$(".loading_box").hide();return}}1==rendering_type&&(myDiagram.model.nodeDataArray=nodeArray,myDiagram.model.linkDataArray=linkArray);myDiagram.addDiagramListener("InitialLayoutCompleted",function(c){c={events:"InitialLayoutCompleted",events_name:"\u56fe\u5e03\u5c40\u521d\u6b21\u52a0\u8f7d\u5b8c\u6210"};
isGraph_events&&callBackToClient(c);download_scale=myDiagram.scale;$(".loading").hide();$(".loading_box").hide();$(".entity_toast").css("left",document.body.clientWidth/2-100);$(".entity_toast").css("top",300);$(".entity_toast").text("\u5e03\u5c40\u5b8c\u6210");$(".entity_toast").show();setTimeout(function(){$(".entity_toast").hide()},200);myDiagram.nodes.each(function(d){d.part.isSelected&&myDiagram.commandHandler.scrollToPart(d);1==d.part.data.isSelected&&(d.part.isSelected=!0)});myDiagram.links.each(function(d){1==
d.part.data.isSelected&&(d.part.isSelected=!0)})});myDiagram.addDiagramListener("ChangedSelection",function(c){ChangedSelection_fuc()});myDiagram.addDiagramListener("ViewportBoundsChanged",function(c){$(".item-inner").hide();4>=myDiagram.scale?sets_sale_num(myDiagram.scale):myDiagram.scale=4;1==rendering_type&&setBottom_nav(graph_tool.getNodesCount(),graph_tool.nodesSelectCount(),graph_tool.nodesVisibleCount(),graph_tool.getEdgesCount(),graph_tool.edgesSelectCount(),graph_tool.edgesVisibleCount());
var d=myDiagram.scale;myDiagram.nodes.each(function(e){myDiagram.viewportBounds.containsRect(e.part.actualBounds);var f=e.findObject("node_icon");e=e.findObject("node_text");null!==f&&(f.opacity=.8>d?!1:!0);null!==e&&(e.opacity=.8>d?!1:!0)});myDiagram.links.each(function(e){var f=e.findObject("link_text");e=e.findObject("link_arrow");null!==f&&(f.opacity=.8>d?!1:!0);null!==e&&(e.opacity=.8>d?!1:!0)})})}
function setLabel_state(a){myDiagram.nodes.each(function(b){var c=b.findObject("entity_label"),d=b.findObject("entity_label2"),e=b.findObject("entity_label3"),f=b.findObject("entity_label_text1"),g=b.findObject("entity_label_text2"),h=b.findObject("entity_label_text3"),k=b.findObject("entity_label_text_x1"),l=b.findObject("entity_label_text_x2");b=b.findObject("entity_label_text_x3");null!==c&&(c.opacity=a,""==f.text&&(c.opacity=0));null!==d&&(d.opacity=a,""==g.text&&(d.opacity=0));null!==e&&(e.opacity=
a,""==h.text&&(e.opacity=0));null!==f&&(f.opacity=a,""==f.text&&(f.opacity=0));null!==g&&(g.opacity=a,""==g.text&&(g.opacity=0));null!==h&&(h.opacity=a,""==h.text&&(h.opacity=0));null!==k&&(k.opacity=a,""==f.text&&(k.opacity=0));null!==l&&(l.opacity=a,""==g.text&&(l.opacity=0));null!==b&&(b.opacity=a,""==h.text&&(b.opacity=0))})}
function setBottom_nav(a,b,c,d,e,f){$(".v_num").text(a);$(".select_v_num").text(b);$(".hide_v_num").text(c);$(".e_num").text(d);$(".selece_e_num").text(e);$(".hide_e_num").text(f)}
function findDistances(a){var b=a.diagram,c=new go.Map;for(b=b.nodes;b.next();)c.set(b.value,Infinity);c.set(a,0);b=new go.Set;b.add(a);for(a=new go.Set;0<b.count;){var d=leastNode(b,c),e=c.get(d);b.delete(d);a.add(d);for(var f=d.findLinksOutOf();f.next();){var g=f.value.getOtherNode(d);if(!a.has(g)){var h=c.get(g),k=e+1;k<h&&(Infinity===h&&b.add(g),c.set(g,k))}}}return c}function nodeSelectionChanged(a){0===myDiagram.selection.count&&myDiagram.links.each(function(b){b.isHighlighted=!1})}
function findShortestPath(a,b){distances=findDistances(a);a=new go.List;for(a.add(b);null!==b;){var c=leastNode(b.findNodesInto(),distances);null!==c&&(distances.get(c)<distances.get(b)?a.add(c):c=null);b=c}a.reverse();return a}function leastNode(a,b){var c=Infinity,d=null;for(a=a.iterator;a.next();){var e=a.value,f=b.get(e);f<c&&(c=f,d=e)}return d}
function highlightPath(a){myDiagram.clearHighlighteds();for(var b=0;b<a.count-1;b++){var c=a.get(b),d=a.get(b+1);c.findLinksTo(d).each(function(e){e.isHighlighted=!0})}};