var menu_x,menu_y,max=$(".slide_content").width()-5,tag=!1,ox=0,left=0,bgleft=0;$(".slide_box").mousedown(function(b){ox=b.pageX-left;tag=!0});$(document).mouseup(function(){tag=!1});
$(".slide_content").mousemove(function(b){tag&&(left=b.pageX-ox,0>=left?left=0:left>max&&(left=max),$(".slide_box").css("left",left),1>parseInt(left/max*400)?($(".scale_num").html("1%"),2==rendering_type?webgl_setZoom(left/max*4):graph_tool.setZomm(.01)):2==rendering_type?webgl_setZoom(left/max*4):graph_tool.setZomm(left/max*4))});
$(".slide_content").click(function(b){tag||(bgleft=$(".slide_content").offset().left,left=b.pageX-bgleft,0>=left?left=0:left>max&&(left=max),$(".slide_box").css("left",left),1>parseInt(left/max*400)?($(".scale_num").html("1%"),2==rendering_type?webgl_setZoom(left/max*4):graph_tool.setZomm(.01)):($(".scale_num").html(parseInt(left/max*400)+"%"),2==rendering_type?webgl_setZoom(left/max*4):graph_tool.setZomm(left/max*4)))});
$(".eye_c").click(function(){"img/eye_h.png"==$(".eye_c").attr("src")?$(".eye_c").attr("src","img/eye_l.png"):$(".eye_c").attr("src","img/eye_h.png");"1px"==$("#myOverviewDIV").css("right")?$("#myOverviewDIV").css("right","-300px"):$("#myOverviewDIV").css("right","1px")});
function setRightMenu_data(b){var a=[],c=graph_tool.nodesSelectCount(),f=graph_tool.edgesSelectCount();if(0<c&&0==f){a=r_node_list.map(function(d){return d});if(2>c){var e=a.indexOf("\u5408\u5e76\u5b9e\u4f53");a.splice(e,1)}"1"==b.is_group&&2==b.merge_type?(a=r_node_list.map(function(d){return d}),e=a.indexOf("\u5408\u5e76\u53f6\u5b50\u8282\u70b9"),a.splice(e,1,"\u5c55\u5f00\u53f6\u5b50\u8282\u70b9")):"1"==b.is_group&&(a=r_node_list.map(function(d){return d}),e=a.indexOf("\u5408\u5e76\u5b9e\u4f53"),
a.splice(e,1,"\u8fd8\u539f\u5b9e\u4f53"))}0<f&&0==c&&(a=r_link_list.map(function(d){return d}),b=graph_tool.getcurrentEdge().type,e=graph_tool.getcurrentEdge().id,"transaction"==b&&-1==e.indexOf("_")&&(a=r_link_list.map(function(d){return d}),a.push("\u8ffd\u8e2a\u5355\u7b14\u94fe\u8def")));0==c&&0==f&&(a=r_blank_list.map(function(d){return d}));0<c&&0<f&&(a=r_node_list.filter(function(d){if("\u53d1\u81f3\u65b0\u56fe"==d)return d}));return a}
function set_R_menu(b){var a="";b.map(function(c){a+="<li onclick='R_menu_li_click(\""+c+"\")' onmouseenter='R_menu_li_in(\""+c+"\")'>"+("\u9009\u4e2d"==c||"\u9690\u85cf"==c?c+"<span style = 'padding-left:90px;'>></span>":c)+"</li>"});$(".R_menu").empty();$(".R_menu").append(a)}function set_R_menu_(b){var a="";b.map(function(c){a+="<li onclick='R_menu_li_click(\""+c+"\")' >"+c+"</li>"});$(".R_menu_").empty();$(".R_menu_").append(a)}
function R_menu_li_in(b){var a=document.getElementById("menu_"),c=graph_tool.getcurrentNodes()[0],f=graph_tool.getcurrentEdges()[0];"\u9009\u4e2d"==b&&c?(a.style.left=menu_x+138+"px",a.style.top=menu_y+96+"px",set_R_menu_(r_node_list_select),$(".R_menu_").show()):"\u9690\u85cf"==b&&c?(a.style.left=menu_x+138+"px",a.style.top=menu_y+128+"px",set_R_menu_(r_node_list_hide),$(".R_menu_").show()):"\u9009\u4e2d"==b&&f?(a.style.left=menu_x+138+"px",a.style.top=menu_y+64+"px",set_R_menu_(r_link_list_select),
$(".R_menu_").show()):"\u9690\u85cf"==b&&f?(a.style.left=menu_x+138+"px",a.style.top=menu_y+32+"px",set_R_menu_(r_link_list_hide),$(".R_menu_").show()):$(".R_menu_").hide()}
function R_menu_li_click(b){switch(b){case "\u590d\u5236":graph_tool.copySelection();break;case "\u5220\u9664":graph_tool.deleteSelection();break;case "\u5168\u9009":graph_tool.selectAll();ChangedSelection_fuc();break;case "\u7c98\u8d34":graph_tool.pasteSelection();break;case "\u53cd\u9009":graph_tool.reverseSelected();break;case "\u5c5e\u6027":send_newGraph("\u5c5e\u6027");break;case "\u9690\u85cf":hideVertex();break;case "\u5168\u90e8\u663e\u793a":show_allEntity();break;case "\u5217\u51fa\u660e\u7ec6":send_newGraph("\u5217\u51fa\u660e\u7ec6");
break;case "\u53d1\u81f3\u65b0\u56fe":send_newGraph("\u53d1\u81f3\u65b0\u56fe");break;case "\u8ffd\u6765\u6e90\u53bb\u5411":send_newGraph("\u8ffd\u6765\u6e90\u53bb\u5411");break;case "\u6dfb\u52a0\u6807\u7b7e":send_newGraph("\u6dfb\u52a0\u6807\u7b7e");break;case "\u521b\u5efa\u5206\u7ec4":send_newGraph("\u521b\u5efa\u5206\u7ec4");break;case "\u65ad\u70b9\u63a5\u7eed":send_newGraph("\u65ad\u70b9\u63a5\u7eed");break;case "\u5217\u51fa\u660e\u7ec6":send_newGraph("\u5217\u51fa\u660e\u7ec6");break;case "\u8ffd\u8e2a\u5355\u7b14\u94fe\u8def":send_newGraph("\u8ffd\u8e2a\u5355\u7b14\u94fe\u8def");
break;case "\u6dfb\u52a0\u8c03\u5355":send_newGraph("\u6dfb\u52a0\u8c03\u5355");break;case "\u5408\u5e76\u53f6\u5b50\u8282\u70b9":merge_child_link();break;case "\u5c55\u5f00\u53f6\u5b50\u8282\u70b9":cacel_merge_child_link();break;case "\u9009\u4e2d\u7aef\u70b9":select_Both_ends();break;case "\u9009\u4e2d\u7aef\u70b9\u548c\u94fe\u63a5":select_Both_ends_links();break;case "\u9009\u4e2d\u94fe\u63a5":select_links();break;case "\u5408\u5e76\u5b9e\u4f53":merge_vertex();break;case "\u8fd8\u539f\u5b9e\u4f53":cacel_merge_node();
break;case "\u94fe\u63a5\u5408\u5e76":merge_link_method();break;case "\u5173\u7cfb\u62d3\u5c55":send_newGraph("\u5173\u7cfb\u62d3\u5c55");break;case "\u9690\u85cf\u672a\u9009\u9879":setEntity2hide();break;case "\u9690\u85cf\u9009\u4e2d\u9879":setSelectEntity2hide()}}
function send_newGraph(b){var a={event_name:b,model:model,entity_type:entity_type,nodeArray:graph_tool.getcurrentNodes(),linkArray:graph_tool.getcurrentEdges(),layout:layout,graph_id:graph_id};if(0<webgl_select_nodes.length){var c=[],f=[];webgl_select_nodes.forEach(function(e){nodeArray.map(function(d){d.key==e&&c.push(d)});linkArray.map(function(d){(d.from==e&&webgl_select_nodes.indexOf(d.to)||d.to==e&&webgl_select_nodes.indexOf(d.from))&&f.push(d)})});a.nodeArray=c;a.linkArray=f;console.log(a)}"\u65ad\u70b9\u63a5\u7eed"==
b&&(a.from_link=get_eids());postmessageToParent(a)}function delete_lable(b){b={currnode:graph_tool.getcurrentNode(),label:graph_tool.getcurrentNode().tags[b-1],event_name:"\u5220\u9664\u5b9e\u4f53\u6807\u7b7e",index:b,graph_id:graph_id};postmessageToParent(b)}
window.oncontextmenu=function(b){if(0<webgl_select_nodes.length){c=["\u53d1\u81f3\u65b0\u56fe"];b.preventDefault();var a=document.getElementById("menu")}else{c=graph_tool.getcurrentNodes()[0];b.preventDefault();a=document.getElementById("menu");var c=setRightMenu_data(c)}if("fxq"==graph_mode){-1!=c.indexOf("\u6dfb\u52a0\u8c03\u5355")&&c.splice(c.indexOf("\u6dfb\u52a0\u8c03\u5355"),1);var f=!1;graph_tool.getcurrentNodes().map(function(e){"account"==e.type&&3!==e.isExpand&&(f=!0)});f&&-1==c.indexOf("\u6dfb\u52a0\u8c03\u5355")&&
c.push("\u6dfb\u52a0\u8c03\u5355")}set_R_menu(c);a.style.display="block";a=480<b.clientY?480:b.clientY;b=1600<b.clientX?1600:b.clientX;menu.style.left=b+"px";menu.style.top=a+"px";menu_x=b;menu_y=a};
window.onclick=function(b){b.stopPropagation();send_newGraph("\u89c6\u56fe\u88ab\u70b9\u51fb\u4e86");document.getElementById("menu").style.display="none";document.getElementById("menu_").style.display="none";0<graph_tool.getcurrentNodes().length||(myDiagram.model.nodeDataArray.map(function(a){myDiagram.model.setDataProperty(a,"fill",a.default_fill);myDiagram.model.setDataProperty(a,"stroke",a.default_stroke)}),myDiagram.model.linkDataArray.map(function(a){myDiagram.model.setDataProperty(a,"fill",
a.default_fill);myDiagram.model.setDataProperty(a,"stroke",a.default_stroke)}))};function search_entity(b){var a;myDiagram.nodes.each(function(c){-1!==c.data.text.indexOf(b)&&(a=c,c.isSelected=!0)});myDiagram.commandHandler.scrollToPart(a)}function get_eids(){console.log(graph_tool.getcurrentNodes());if(0<graph_tool.getcurrentNodes().length){var b=[],a=graph_tool.getcurrentNodes()[0];myDiagram.model.linkDataArray.map(function(c){c.to==a.key&&b.push(c)});return b}}
function setView(){var b=document.documentElement.clientWidth;1380<b&&$(".Lcss").css("margin-left","14%");1600<b&&$(".Lcss").css("margin-left","20%")}setView();$(".zoom_s").click(function(){2==rendering_type?webgl_decreaseZoom():graph_tool.decreaseZoom()});$(".zoom_f").click(function(){2==rendering_type?webgl_increaseZoom():graph_tool.increaseZoom()});function sets_sale_num(b){$(".slide_box").css("left",parseInt(100*b)/400*130);$(".scale_num").html(parseInt(100*b)+"%")};