var GO=go.GraphObject.make,def_color="#ccc";function convertPathPatternToShape(a){return a?PathPatterns.get(a):null}function convertPathPatternToColor(a){a=convertPathPatternToShape(a);return null!==a?a.stroke:"transparent"}var PathPatterns=new go.Map;
function definePathPattern(a,b,c,d,e){if("string"!==typeof a||"string"!==typeof b)throw Error("invalid name or geometry string argument: "+a+" "+b);void 0===c&&(c="black");void 0===d&&(d=1);void 0===e&&(e="square");PathPatterns.set(a,GO(go.Shape,{geometryString:b,fill:"transparent",stroke:c,strokeWidth:d,strokeCap:e}))}definePathPattern("Dash","M0 0 M3 0 L6 0","#A01CBB");
function SmarterForceDirectedLayout(){go.ForceDirectedLayout.call(this);this.radial=new RadialLayout;this.radial.layerThickness=200}go.Diagram.inherit(SmarterForceDirectedLayout,go.ForceDirectedLayout);SmarterForceDirectedLayout.prototype.needsClusterLayout=function(){go.ForceDirectedLayout.prototype.needsClusterLayout.call(this)&&(this.radial.network=this.network,this.radial.doLayout(this.diagram));return!1};
function froce_layout(){myDiagram.div=null;myDiagram=GO(go.Diagram,"myDiagramDiv",{initialAutoScale:go.Diagram.Uniform,"undoManager.isEnabled":!0,"animationManager.isEnabled":!1,layout:GO(go.ForceDirectedLayout,{defaultSpringLength:50,maxIterations:100,isOngoing:!1})});myOverview.div=null;myOverview=GO(go.Overview,"myOverviewDIV",{observed:myDiagram});myDiagram.nodeTemplateMap.add("",GO(go.Node,"Vertical",{visible:!0,layerName:"Foreground",click:function(a,b){},doubleClick:function(){send_newGraph("\u5c5e\u6027")}},
new go.Binding("visible"),GO(go.Shape,"Ellipse",{name:"node_shape",stroke:"#fff",fill:"#006ADF",width:60,cursor:"pointer",height:60,portId:""},{toolTip:tooltipTemplate},new go.Binding("stroke","d_stroke"),(new go.Binding("fill","isHighlighted",function(a,b){return a?"red":b.part.data.d_fill})).ofObject(),new go.Binding("width"),new go.Binding("height")),GO(go.Picture,{name:"node_icon",source:"./img/account.svg",margin:new go.Margin(-40,0,0,0),opacity:1},new go.Binding("source","icon",geoFunc),new go.Binding("width",
"width",function(a){return.6*a}),new go.Binding("height","height",function(a){return.5*a}),new go.Binding("margin","height",function(a){return new go.Margin(.78*-a,0,0,0)})),GO(go.Panel,"Auto",{name:"node_text",margin:12,opacity:!1},new go.Binding("margin","width",function(a){return 12*a/60*1.2}),GO(go.Shape,"Rectangle",{fill:null,stroke:null,margin:new go.Margin(5,0,0,0)},(new go.Binding("fill","isSelected",function(a){return a?"#FFC106":null})).ofObject("")),GO(go.TextBlock,{margin:6,font:"12px helvetica, bold Arial, sans-serif"},
new go.Binding("text","text",function(a){return a}),(new go.Binding("stroke","isSelected",function(a){return a?"#fff":"#333"})).ofObject(""),new go.Binding("font","fontSize",function(a){return a+"px helvetica, bold Arial, sans-serif"}))),{selectionAdornmentTemplate:GO(go.Adornment,"Vertical",GO(go.Shape,"RoundedRectangle",{width:100,height:130,fill:null,stroke:null,strokeWidth:5,margin:new go.Margin(0,0,0,0)}),GO(go.Placeholder))},{selectionAdorned:!1}));myDiagram.linkTemplateMap.add("",GO(go.Link,
{cursor:"pointer"},{doubleClick:function(){send_newGraph("\u5c5e\u6027")}},{toolTip:tooltipTemplate_link},GO(go.Shape,{name:"link_arrow",toArrow:"standard",stroke:"#BDBDBD",fill:"#BDBDBD",opacity:!1},new go.Binding("fill","d_stroke",function(a){return a}),new go.Binding("strokeWidth","stroke_width"),new go.Binding("stroke","d_stroke",function(a){return a}),new go.Binding("visible","dir",function(a){if(0===a)return!1;if(1===a)return!0;if(2===a)return!1;if(3===a)return!0})),GO(go.Shape,{name:"link_arrow",
fromArrow:"Backward",stroke:"#BDBDBD",fill:"#BDBDBD",opacity:!1},new go.Binding("fill","d_stroke",function(a){return a}),new go.Binding("stroke","d_stroke",function(a){return a}),new go.Binding("strokeWidth","stroke_width"),new go.Binding("visible","dir",function(a){if(0===a||1===a)return!1;if(2===a||3===a)return!0})),GO(go.Shape,{name:"edge_shape",opacity:1,isPanelMain:!0,stroke:"#BDBDBD",strokeWidth:1,fill:"#BDBDBD"},new go.Binding("fill","d_stroke",function(a){return a}),new go.Binding("stroke",
"d_stroke",function(a){return a}),new go.Binding("strokeWidth","stroke_width")),{},GO(go.TextBlock,{name:"link_text",text:"",textAlign:"center",font:"10px helvetica, nomal Arial, sans-serif",stroke:"#333",editable:!1,opacity:!1,segmentOffset:new go.Point(10,NaN),segmentOrientation:go.Link.OrientUpleft,margin:4},new go.Binding("text"),new go.Binding("stroke","fontColor"),new go.Binding("font","fontSize",function(a){return a+"px helvetica, nomal Arial, sans-serif"}))));myDiagram.linkTemplateMap.add("c",
GO(go.Link,go.Link.Bezier,{fromEndSegmentLength:150,toEndSegmentLength:150,adjusting:go.Link.End},{doubleClick:function(){send_newGraph("\u5c5e\u6027")}},{toolTip:tooltipTemplate_link},(new go.Binding("points")).makeTwoWay(),GO(go.Shape,{opacity:1,isPanelMain:!0,stroke:"#BDBDBD",strokeWidth:1,fill:"#BDBDBD"},new go.Binding("fill","d_stroke"),new go.Binding("stroke","d_stroke")),GO(go.Shape,{isPanelMain:!0,stroke:"white",strokeWidth:3,name:"PIPE",strokeDashArray:[10,10],opacity:0}),GO(go.TextBlock,
{name:"link_text",textAlign:"center",stroke:"#000",visible:!1},new go.Binding("font","font_size",function(a){return a+"px helvetica, bold Arial, sans-serif"}),new go.Binding("text","text",function(a){return a.replace(/(\r\n)|(\n)/g,"  ")})),GO(go.Shape,{name:"link_arrow",toArrow:"standard",stroke:"#BDBDBD",fill:"#BDBDBD",visible:!1},new go.Binding("fill","d_stroke"),new go.Binding("stroke","d_stroke"),new go.Binding("visible","dir",function(a){if(0===a)return!1;if(1===a)return!0;if(2===a)return!1;
if(3===a)return!0})),GO(go.Shape,{name:"link_arrow",fromArrow:"Backward",stroke:"#BDBDBD",fill:"#BDBDBD",visible:!1},new go.Binding("fill","d_stroke"),new go.Binding("stroke","d_stroke"),new go.Binding("visible","dir",function(a){if(0===a||1===a)return!1;if(2===a||3===a)return!0}))))};