function SankeyLayout(){go.LayeredDigraphLayout.call(this)}go.Diagram.inherit(SankeyLayout,go.LayeredDigraphLayout);SankeyLayout.prototype.createNetwork=function(){this.diagram.nodes.each(function(a){var b=getAutoHeightForNode(a),c="normal "+Math.max(6,Math.round(b/8))+"pt Segoe UI, sans-serif",d=a.findObject("SHAPE"),e=a.findObject("TEXT"),f=a.findObject("TEXTNAME");a=a.findObject("LTEXT");d&&(d.height=b);e&&(e.font=c,f.font=c);a&&(a.font=c)});return go.LayeredDigraphLayout.prototype.createNetwork.call(this)};
function getAutoHeightForNode(a){for(var b=0,c=a.findLinksInto();c.next();){var d=c.value;b+=d.computeThickness()}var e=0;for(c=a.findLinksOutOf();c.next();)d=c.value,e+=d.computeThickness();a=Math.max(b,e);10>a&&(a=5);return a}
SankeyLayout.prototype.nodeMinColumnSpace=function(a,b){if(null===a.node){if(1<=a.edgesCount){b=1;for(a=a.edges;a.next();){var c=a.value;if(null!=c.link){a=c.link.computeThickness();a>b&&(b=a);break}}return Math.max(2,Math.ceil(b/this.columnSpacing))}return 10}return go.LayeredDigraphLayout.prototype.nodeMinColumnSpace.call(this,a,b)};SankeyLayout.prototype.nodeMinLayerSpace=function(a,b){return null===a.node?300:go.LayeredDigraphLayout.prototype.nodeMinLayerSpace.call(this,a,b)};
SankeyLayout.prototype.assignLayers=function(){go.LayeredDigraphLayout.prototype.assignLayers.call(this);for(var a=this.maxLayer,b=this.network.vertexes.iterator;b.next();){var c=b.value;0==c.destinationVertexes.count&&(c.layer=0);0==c.sourceVertexes.count&&(c.layer=a)}};SankeyLayout.prototype.commitLayout=function(){go.LayeredDigraphLayout.prototype.commitLayout.call(this);for(var a=this.network.edges.iterator;a.next();){var b=a.value.link;b&&b.curve===go.Link.Bezier&&b.invalidateRoute()}};
var animation=new go.Animation;animation.easing=go.Animation.EaseLinear;
function sankey_layout(){graph_layout_type=1;myDiagram.div=null;myDiagram=GO(go.Diagram,"myDiagramDiv",{initialAutoScale:go.Diagram.Uniform,"animationManager.isEnabled":!1,ModelChanged:function(a){},layout:GO(SankeyLayout,{setsPortSpots:!1,direction:0,initializeOption:go.LayeredDigraphLayout.InitDepthFirstIn,packOption:go.LayeredDigraphLayout.PackStraighten||go.LayeredDigraphLayout.PackMedian,layerSpacing:void 0==option.layerSpacing?300:option.layerSpacing,columnSpacing:2})});myOverview.div=null;
myOverview=GO(go.Overview,"myOverviewDIV",{observed:myDiagram});myDiagram.nodeTemplateMap.add("",GO(go.Node,go.Panel.Horizontal,{doubleClick:function(){send_newGraph("\u5c5e\u6027")}},(new go.Binding("location","loc",go.Point.parse)).makeTwoWay(go.Point.stringify),GO(go.Shape,{name:"SHAPE",figure:"Rectangle",stroke:null,fromSpot:go.Spot.RightSide,toSpot:go.Spot.LeftSide,portId:"",cursor:"pointer",fromLinkable:!1,toLinkable:!1,width:10},{toolTip:tooltipTemplate},new go.Binding("fill","d_fill"),new go.Binding("stroke",
"d_stroke")),GO(go.TextBlock,{name:"node_text",font:"normal 6pt Segoe UI, sans-serif",stroke:"#333",opacity:!1},new go.Binding("text","text",function(a){return a.replace(/[\r\n]/g,"")}),new go.Binding("stroke","fontColor"),new go.Binding("font","fontSize",function(a){return a+"px helvetica, nomal Arial, sans-serif"})),{selectionAdornmentTemplate:GO(go.Adornment,"Auto",GO(go.Shape,"RoundedRectangle",{width:100,height:130,fill:null,stroke:null,strokeWidth:5,margin:new go.Margin(0,0,0,0)}),GO(go.Placeholder))}));
GO(go.Adornment,"Link",GO(go.Shape,{isPanelMain:!0,fill:null,stroke:"blue",strokeWidth:3}));myDiagram.linkTemplate=GO(go.Link,go.Link.Bezier,{fromEndSegmentLength:150,toEndSegmentLength:150,adjusting:go.Link.End},{doubleClick:function(){send_newGraph("\u5c5e\u6027")}},{},(new go.Binding("points")).makeTwoWay(),GO(go.Shape,{opacity:1,isPanelMain:!0,stroke:"#BDBDBD",strokeWidth:1,fill:"#BDBDBD"},new go.Binding("fill","d_fill"),new go.Binding("stroke","d_stroke")),GO(go.Shape,{isPanelMain:!0,stroke:"white",
strokeWidth:3,name:"PIPE",strokeDashArray:[10,10],opacity:0}),GO(go.TextBlock,{name:"link_text"},"2/3",{segmentIndex:NaN,segmentFraction:.5,font:" 6pt Segoe UI, sans-serif",stroke:"#333"},new go.Binding("text","text",function(a){return a.replace(/(\r\n)|(\n)/g,"  ")}),new go.Binding("stroke","fontColor"),new go.Binding("font","fontSize",function(a){return a+"px helvetica, nomal Arial, sans-serif"})),GO(go.Shape,{name:"link_arrow",toArrow:"standard",stroke:"#BDBDBD",fill:"#BDBDBD"},new go.Binding("fill",
"d_fill"),new go.Binding("stroke","d_stroke")))};